fragment ProductTags on Product {
  productTags {
    nodes {
      databaseId
      slug
      name
      count
    }
  }
}

# ⚡ ОПТИМИЗИРАН за Grid - само slug и име
fragment ProductTagsGrid on Product {
  productTags {
    nodes {
      slug
      name
    }
  }
}