fragment ProductCategories on Product {
  productCategories {
    nodes {
      databaseId
      slug
      name
      count
      parent {
        node {
          slug
        }
      }
    }
  }
}
