fragment Terms on Product {
  terms(first: 100) {
    nodes {
      taxonomyName
      slug
      name
      databaseId
    }
  }
}

# ⚡ ОПТИМИЗИРАН за Grid - само 10 terms
fragment TermsGrid on Product {
  terms(first: 10) {
    nodes {
      taxonomyName
      slug
      name
    }
  }
}
