query getProductsCount($slug: [String]) {
  products(first: 1000, where: { categoryIn: $slug, visibility: VISIBLE, status: "publish" }) {
    pageInfo {
      hasNextPage
      hasPreviousPage
    }
    edges {
      cursor
    }
  }
}
