query getProductsCount($slug: [String], $productTag: [String]) {
  products(first: 1000, where: { categoryIn: $slug, tagIn: $productTag, visibility: VISIBLE, status: "publish" }) {
    pageInfo {
      hasNextPage
      hasPreviousPage
    }
    edges {
      cursor
    }
  }
}
