# import "./fragments/ProductTagsFragment.gql"
# import "./fragments/PwbBrandsFragment.gql"
# import "./fragments/ProductAttributeFragment.gql"

query getProduct($slug: ID!) {
  product(id: $slug, idType: SLUG) {
    name
    type
    databaseId
    id
    metaData {
      id
      key
      value
    }
    slug
    sku
    description
    rawDescription: description(format: RAW)
    shortDescription
    ...ProductWithAttributes
    ...ProductCategories
    ...ProductTags
    ...PwbBrands
    ...Terms
    ...SimpleProduct
    ...VariableProduct
    ...ExternalProduct
    ...SeoProductFragment
    related(first: 5) {
      nodes {
        ...SimpleProduct
        ...VariableProduct
        ...ExternalProduct
      }
    }
    reviews {
      averageRating
      edges {
        rating
        node {
          ...Comment
        }
      }
    }
  }
}

fragment Comment on Comment {
  content
  id
  date
  author {
    node {
      name
      avatar {
        url
      }
    }
  }
}
